title: twalcari
description: Notes made while programming

url: http://twalcari.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html

social:
   github: twalcari
   linkedin: thijswalcarius

google_analytics: "UA-82913-8"
